# Generated by Django 4.2.4 on 2023-08-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=250, verbose_name="название рассылки"),
                ),
                (
                    "email_subject",
                    models.CharField(max_length=250, verbose_name="тема письма"),
                ),
                ("email_body", models.TextField(verbose_name="содержание письма")),
                (
                    "mailing_time",
                    models.DateTimeField(auto_now=True, verbose_name="время рассылки"),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("daily", "Ежедневная"),
                            ("weekly", "Раз в неделю"),
                            ("monthly", "Раз в месяц"),
                        ],
                        max_length=20,
                        verbose_name="периодичность",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("started", "Запущена"),
                            ("done", "Завершена"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="статус рассылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
    ]
