# Generated by Django 4.2.4 on 2023-08-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recipient", "0001_initial"),
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="recipient",
            field=models.ManyToManyField(
                related_name="mailing",
                to="recipient.recipient",
                verbose_name="получатель",
            ),
        ),
    ]
