# Generated by Django 4.2.4 on 2023-08-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="имя")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="отчество"
                    ),
                ),
                ("last_name", models.CharField(max_length=150, verbose_name="фамилия")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="контактный email"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="комментарий"),
                ),
            ],
            options={
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
            },
        ),
    ]
